// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSWw2_u8D2M5V2L_brgShd7nHIsuTuQag',
    appId: '1:692080182594:web:f6b9113026cec59e8274db',
    messagingSenderId: '692080182594',
    projectId: 'attendance01-d1e8b',
    authDomain: 'attendance01-d1e8b.firebaseapp.com',
    storageBucket: 'attendance01-d1e8b.appspot.com',
    measurementId: 'G-3S9HV7R3WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvFD1cHuxzSbt1zRZRABt30HYuFYvpOOg',
    appId: '1:692080182594:android:370ae6661fadd1a58274db',
    messagingSenderId: '692080182594',
    projectId: 'attendance01-d1e8b',
    storageBucket: 'attendance01-d1e8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYYF8wifWzEuteq-fhGY9_LuIv3O3TWMk',
    appId: '1:692080182594:ios:fc35faf89d50b8618274db',
    messagingSenderId: '692080182594',
    projectId: 'attendance01-d1e8b',
    storageBucket: 'attendance01-d1e8b.appspot.com',
    iosBundleId: 'com.example.firebase03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYYF8wifWzEuteq-fhGY9_LuIv3O3TWMk',
    appId: '1:692080182594:ios:fc35faf89d50b8618274db',
    messagingSenderId: '692080182594',
    projectId: 'attendance01-d1e8b',
    storageBucket: 'attendance01-d1e8b.appspot.com',
    iosBundleId: 'com.example.firebase03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSWw2_u8D2M5V2L_brgShd7nHIsuTuQag',
    appId: '1:692080182594:web:20fa58f4bed0eb498274db',
    messagingSenderId: '692080182594',
    projectId: 'attendance01-d1e8b',
    authDomain: 'attendance01-d1e8b.firebaseapp.com',
    storageBucket: 'attendance01-d1e8b.appspot.com',
    measurementId: 'G-0JDN5XM84X',
  );
}
